highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
environment: prod
markdown: kramdown
url: "https://gavayres.github.io"  # Sitemap base URL.
plugins:
  - jekyll-sitemap
  - jekyll-feed
kramdown:
  math_engine: mathjax
include: [_pages]
include: [_notes]
